### PR TITLE
RATIS-1443 Shade all Netty Native libraries

### PR DESCRIPTION
**Pull request by martin-g**

### CODE REVIEW

**Review by szetszwo — COMMENTED** [review]
@martin-g , the change looks good.  Just a question:

Before this change, we have
```
META-INF/native/
META-INF/native/libnetty_resolver_dns_native_macos_x86_64.jnilib
META-INF/native/libnetty_tcnative_linux_aarch_64.so
META-INF/native/libnetty_transport_native_epoll_aarch_64.so
META-INF/native/libnetty_transport_native_epoll_x86_64.so
META-INF/native/libnetty_transport_native_kqueue_x86_64.jnilib
META-INF/native/liborg_apache_ratis_thirdparty_netty_tcnative_linux_x86_64.so
META-INF/native/liborg_apache_ratis_thirdparty_netty_tcnative_osx_x86_64.jnilib
META-INF/native/liborg_apache_ratis_thirdparty_netty_transport_native_epoll_x86_64.so
META-INF/native/liborg_apache_ratis_thirdparty_netty_transport_native_kqueue_x86_64.jnilib
META-INF/native/org_apache_ratis_thirdparty_netty_tcnative_windows_x86_64.dll
```

After the change, we now have
```
META-INF/native/
META-INF/native/libnetty_resolver_dns_native_macos_x86_64.jnilib
META-INF/native/libnetty_tcnative_linux_aarch_64.so
META-INF/native/libnetty_transport_native_epoll_aarch_64.so
META-INF/native/libnetty_transport_native_epoll_x86_64.so
META-INF/native/libnetty_transport_native_kqueue_x86_64.jnilib
META-INF/native/liborg_apache_ratis_thirdparty_netty_resolver_dns_native_macos_x86_64.jnilib
META-INF/native/liborg_apache_ratis_thirdparty_netty_tcnative_linux_aarch_64.so
META-INF/native/liborg_apache_ratis_thirdparty_netty_tcnative_linux_x86_64.so
META-INF/native/liborg_apache_ratis_thirdparty_netty_tcnative_osx_x86_64.jnilib
META-INF/native/liborg_apache_ratis_thirdparty_netty_transport_native_epoll_aarch_64.so
META-INF/native/liborg_apache_ratis_thirdparty_netty_transport_native_epoll_x86_64.so
META-INF/native/liborg_apache_ratis_thirdparty_netty_transport_native_kqueue_x86_64.jnilib
META-INF/native/org_apache_ratis_thirdparty_netty_tcnative_windows_x86_64.dll
```
All the libnetty_xxx files have corresponding liborg_apache_ratis_thirdparty_netty_xxx file now.  Do we have to remove the libnetty_xxx files?

**Comment by martin-g** [comment]
Hm, maybe I didn't test this properly ?!
I tested it with these commands:
```
$ mvn clean package
$ ls -la misc/target/classes/META-INF/native/
total 10168
drwxrwxr-x 2 martin martin    4096 ное 30 13:06 .
drwxrwxr-x 3 martin martin    4096 ное 30 13:06 ..
-rw-r--r-- 1 martin martin   73544 апр  1  2021 liborg_apache_ratis_thirdparty_netty_resolver_dns_native_macos_x86_64.jnilib
-rw-r--r-- 1 martin martin 2156176 мар 29  2021 liborg_apache_ratis_thirdparty_netty_tcnative_linux_aarch_64.so
-rw-r--r-- 1 martin martin 2636808 мар 29  2021 liborg_apache_ratis_thirdparty_netty_tcnative_linux_x86_64.so
-rw-r--r-- 1 martin martin 2751864 мар 29  2021 liborg_apache_ratis_thirdparty_netty_tcnative_osx_x86_64.jnilib
-rw-r--r-- 1 martin martin   92424 апр  1  2021 liborg_apache_ratis_thirdparty_netty_transport_native_epoll_aarch_64.so
-rw-r--r-- 1 martin martin   85866 апр  1  2021 liborg_apache_ratis_thirdparty_netty_transport_native_epoll_x86_64.so
-rw-r--r-- 1 martin martin   77616 апр  1  2021 liborg_apache_ratis_thirdparty_netty_transport_native_kqueue_x86_64.jnilib
-rw-r--r-- 1 martin martin 2457088 мар 29  2021 org_apache_ratis_thirdparty_netty_tcnative_windows_x86_64.dll
```
Where do you see the old files (`libnetty_***.*`) ?

**Comment by martin-g** [comment]
I see!
The old ones are in the .jar file!
Let me see how to not package them!

**Comment by martin-g** [comment]
@szetszwo Please check the new commit!

**Comment by szetszwo** [comment]
> The old ones are in the .jar file!

Yes, I mean the jar files as you mentioned in the JIRA.

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Pull request merged**
