### PR TITLE
RATIS-1344. ratis-thirdparty: remove DISCLAIMER and fix README.md for…

### PR DESCRIPTION
**Pull request by cnauroth**
… TLP

## What changes were proposed in this pull request?

Remove ratis-thirdparty incubator disclaimers and update references to TLP core ratis repo.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/RATIS-1344

## How was this patch tested?

Confirmed build locally.  Verified all new links are correct.

### CODE REVIEW

**Comment by cnauroth** [comment]
Question: README.md mentions a ratis-thirdparty-hadoop module, but I don't see that.  (I do see ratis-hadoop in the core ratis repo.)  Should I remove mention of ratis-thirdparty-hadoop here?

**Comment by szetszwo** [comment]
@cnauroth , thanks a lot for working on this.

>  README.md mentions a ratis-thirdparty-hadoop module, ...

ratis-thirdparty-hadoop was removed by https://issues.apache.org/jira/browse/RATIS-933 .  Please remove it from README.md as well.

**Comment by cnauroth** [comment]
@szetszwo , thanks for confirming.  I pushed up another change to remove mention of ratis-thirdparty-hadoop.

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Pull request merged**
