### PR TITLE
RATIS-1664. Exclude org.slf4j.* in ratis-thirdparty-misc

### PR DESCRIPTION
**Pull request by codings-dan**
see https://issues.apache.org/jira/browse/RATIS-1664

### CODE REVIEW

**Comment by szetszwo** [comment]
@codings-dan , we should exclude org.slf4j.* but not relocate it.  The thirdparty jar should only include the shaded classes but not all the classes.

**Comment by codings-dan** [comment]
@szetszwo Thanks for helping review, I have updated code, PTAL

**Review by szetszwo — COMMENTED** [review]
@codings-dan , thanks for the update.  The change looks good.

Could you also address @adoroszlai 's comment on JIRA; see below?

> Some other dependencies are not relocated:
> - com.google.api.grpc:proto-google-common-protos
> - io.perfmark
> - org.acplt
>
> The first one also has several proto definitions.

**Comment by szetszwo** [comment]
For `io.perfmark` and `org.acplt`, we probably should exclude them but not relocate them.

**Comment by codings-dan** [comment]
@szetszwo I have updated the code. For `io.perfmark` and `org.acplt`, I know we should exclude them, but I don't understand what we should do for `com.google.api.grpc:proto-google-common-protos` and just exclude it. If incorrent, please let me know, thanks!

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

Just tried the change.  Successfully compiled Ratis.  Everything worked fine.

**Pull request merged**
