### PR TITLE
RATIS-2202 Bump ratis-thirdparty version to 1.0.8-SNAPSHOT after 1.0.7 release

### PR DESCRIPTION
**Pull request by OneSizeFitsQuorum**

### CODE REVIEW

**Comment by OneSizeFitsQuorum** [comment]
@adoroszlai @szetszwo PTAL

**Review by adoroszlai — APPROVED** [review]
Thanks @OneSizeFitsQuorum for the patch.

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

Let's create a JIRA.  It is easier to track.

**Comment by OneSizeFitsQuorum** [comment]
| Let's create a JIRA. It is easier to track.

done @szetszwo 

Thanks @szetszwo @adoroszlai for reviewing this~

**Pull request merged**
