### PR TITLE
RATIS-1343. Add basic CI check for ratis-thirdparty

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Add a basic Github Actions check to build the package and run existing smoketests.

https://issues.apache.org/jira/browse/RATIS-1343

## How was this patch tested?

Push to fork:
https://github.com/adoroszlai/ratis-thirdparty/actions/runs/661309748

```
...
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
...
[INFO] BUILD SUCCESS
```

### CODE REVIEW

**Comment by adoroszlai** [comment]
@mukul1987 can you please review?

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Comment by adoroszlai** [comment]
Thanks @szetszwo for reviewing and committing it.

**Comment by szetszwo** [comment]
```
commit bceb0191706022531a87630011d89e3d4ce4df50 (HEAD -> master, origin/master, origin/HEAD)
Merge: b085f91 90d8edd
Author: Tsz-Wo Nicholas Sze <szetszwo@apache.org>
Date:   Thu Mar 18 21:54:13 2021 +0800

    RATIS-1343. Add basic CI check for ratis-thirdparty. (#13)
```
Somehow the commit is associated with my email address.  Will re-merge this.

**Pull request merged**
