### PR TITLE
RATIS-1595.Shade dropwizard 4.x in ratis-thirdparty

### PR DESCRIPTION
**Pull request by codings-dan**
see https://issues.apache.org/jira/browse/RATIS-1595

### CODE REVIEW

**Comment by codings-dan** [comment]
@szetszwo I'm not very sure if this change can meet our needs, please help to take a look, thank you!

**Comment by szetszwo** [comment]
@codings-dan , let me work on this.  Could you work on the code change in the ratis master branch instead?

**Comment by szetszwo** [comment]
@codings-dan , please see https://github.com/apache/ratis-thirdparty/pull/34

**Comment by codings-dan** [comment]
> @codings-dan , let me work on this. Could you work on the code change in the ratis master branch instead?

will do, I will release thirdparty 1.0.1 first

**Pull request closed without merging**
