### PR TITLE
RATIS-383. Shade native library tcnative for grpc/netty in Ratis-Thir…

### PR DESCRIPTION
**Pull request by xiaoyuyao**
…dparty.

### CODE REVIEW

**Comment by joshelser** [comment]
Thanks for putting this together @xiaoyuyao. When I was putting this together, I had concerns as to how the tcnative stuff worked, but, frankly, didn't know how to even go about verifying it.

While I can look at your patch and understand the changes you've made, I still don't know how to say if they'll work as expected. Can you enlighten me?

**Comment by xiaoyuyao** [comment]
This will be used later on to enable mTLS for gRPC based services like Ratis and Ozone DN services. (See the lined JIRA in RATIS-383)

What this patch does is to add the ratis-thirdparty prefix the jar and native libraries so that they linked properly.

**Comment by joshelser** [comment]
> What this patch does is to add the ratis-thirdparty prefix the jar and native libraries so that they linked properly.

How can we tell if this is working? Can we write a test in ratis-thirdparty to show this is working as-expected?

For the other changes, we would verify thirdparty is good based on the ability to build+test the core Ratis build. If we have something manual to run in the core of Ratis to validate this change, that's OK too.

**Comment by xiaoyuyao** [comment]
I have a prototype in ozone datanode container service (GRPC) with mTLS that works with this change. Otherwise, tcnative will not be linked properly (missing the shaded prefix). 

I will attach a patch to https://issues.apache.org/jira/browse/RATIS-246 along with a unit test.

**Comment by joshelser** [comment]
> I have a prototype in ozone datanode container service (GRPC) with mTLS that works with this change. Otherwise, tcnative will not be linked properly (missing the shaded prefix).

That's awesome. Thanks @xiaoyuyao! Is this something simple that you can give me instructions to validate?

There is an 0.1.0 rc1 VOTE on-going now. Should we get this fix (validated by your test) into this release? Or can we wait for it?

**Comment by adoroszlai** [comment]
I think this can be closed due to 84dfcde.

**Comment by szetszwo** [comment]
@adoroszlai , sure, let's close this.  Thanks for checking it.

**Pull request closed without merging**
