### PR TITLE
RATIS-1342. Upgrade Netty to 4.1.60.Final

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Bump Netty version to latest 4.1 release with fix for:

 * https://github.com/netty/netty/security/advisories/GHSA-5mcr-gq6c-3hq2
 * https://github.com/netty/netty/security/advisories/GHSA-wm47-8v5p-wjpj

https://issues.apache.org/jira/browse/RATIS-1342

## How was this patch tested?

Tested locally: built `ratis-thirdparty-misc`, built Ratis with it.  Ran Ratis tests and some Ozone acceptance tests using this custom build.

### CODE REVIEW

**Review by risdenk — APPROVED** [review]

**Comment by cnauroth** [comment]
+1 (non-binding)

I checked out the change locally.  The build was successful and all tests passed.

Thank you for the change, @adoroszlai .

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Comment by szetszwo** [comment]
Thanks @adoroszlai for working on this.

Thanks also @risdenk and @cnauroth for reviewing the change.
 
I just have merged this pull request.

**Comment by adoroszlai** [comment]
Thanks @cnauroth and @risdenk for the review, @szetszwo for merging it.

**Pull request merged**
